FREQUENT_WORDS = {
    "a": ["above", "afraid", "against", "agree", "allow", "answer", "apple",
          "arm", "art", "able", "act", "after", "age", "air", "among",
          "anger", "arrange", "atom", "about", "add", "again", "ago",
          "always", "animal", "appear", "area", "arrive", "ask"],
    "b": ["baby", "ball", "bar", "bat", "beat", "been", "begin", "bell",
          "blood", "board", "bone", "bot", "box", "bread", "bring",
          "brother", "build", "buy", "burn", "broad", "break", "boy",
          "bottom", "book", "boat", "blow", "black", "big", "best", "behind",
          "before", "beauty", "base", "band", "back", "bad", "bank", "basic",
          "bear", "bed", "began", "believe", "better", "bird", "block", "body",
          "born"],
    "c": ["call", "car", "carry", "catch", "cell", "chair", "character",
          "check", "child", "claim", "collect", "column", "cool", "corner",
          "cotton", "cow", "cry", "coat", "compare", "cross", "cold", "color",
          "common", "complete", "consider", "cook", "cost", "count", "crowd",
          "cold"],
    "d": ["dad", "dark", "deal", "decide", "develop", "direct", "divide",
          "dollar", "door", "draw", "drink", "dance", "discuss", "drive",
          "danger", "death", "difficult", "dog", "done", "down", "dress"],
    "e": ["each", "earth", "egg", "electric", "equal", "engine", "example",
          "exercise", "experiment", "ear", "edge", "element", "equate",
          "evening", "every", "effect", "energy", "especially", "exact",
          "excite", "experience"],
    "f": ["face", "famous", "father", "feet", "fig", "find", "first", "floor",
          "food", "form", "free", "fruit", "fact", "far", "favor", "fell",
          "fight", "fine", "fish", "flow", "foot", "forward", "fresh", "full",
          "fair", "farm", "fear", "felt", "figure", "finger", "fit", "flower",
          "for", "found", "friend", "fun", "fall", "fast", "feed", "finish",
          "fly", "family", "front"],
    "g": ["game", "general", "glad", "good", "gray", "group", "garden",
          "gentle", "glass", "got", "great", "grow", "gas", "get", "go",
          "green", "guess", "girl", "gold", "grand"],
    "h": ["had", "happy", "he", "heat", "here", "history", "hope", "how",
          "hurry", "hair", "hard", "head", "heavy", "high", "hit", "horse",
          "huge", "half", "has", "hear", "held", "hill", "hot", "human", "hand",
          "hat", "heard", "help", "hundred"],
    "i": ["i", "in", "insect", "iron", "ice", "inch", "instant", "is", "idea",
          "include", "instrument", "island", "if", "indicate", "interest"],
    "j": ["job", "join", "joy", "jump", "just"],
    "k": ["keep", "king", "kept", "key", "knew", "kill", "know", "kind"],
    "l": ["lady", "last", "lead", "left", "letter", "light", "listen", "lone",
          "loud", "lake", "late", "learn", "leg", "level", "like", "little",
          "long", "love", "land", "laugh"],
    "m": ["machine", "make", "market", "matter", "measure", "metal", "milk",
          "miss", "money", "most", "mouth", "must", "made", "man", "mass",
          "may", "meat", "method", "million", "mix", "mix", "month", "mother",
          "move", "magnet", "many", "Meet"],
    "n": ["name", "necessary", "new", "noise", "note", "number", "nation",
          "neck", "next", "noon", "nothing", "numeral", "natual", "need",
          "night", "notice", "nature", "neighbor", "nine", "north", "near",
          "now", "never"],
    "o": ["object", "oil", "only", "order", "out", "observe", "offer", "old",
          "open", "organ", "over", "occur", "office", "operate", "original",
          "own", "ocean", "often", "once", "opposite", "other", "one", "our"],
    "p": ["page", "paper", "paper", "pattern", "phrase", "piece", "planet",
          "point", "print", "process", "proper", "push", "person", "picture",
          "pair", "parent", "party", "people", "picture", "place", "plane",
          "play", "poem", "population", "position", "pound", "pretty",
          "problem", "product"],
    "q": ["question", "quick", "quite"],
    "r": ["race", "rain", "range", "read", "reason", "repeat", "rich", "ring",
          "road", "room", "rose", "radio", "rather", "receive", "reply",
          "region", "record", "remember", "represent", "result", "right",
          "rope", "run"],
    "s": ["safe", "salt", "sat", "say", "science", "seed", "second", "sentence",
          "several", "share", "same", "scale", "score", "season", "self",
          "sense", "settle", "shall", "sharp", "sail", "sand", "saw", "seat",
          "school", "sea", "see", "segment", "sell", "serve", "seven", "shape",
          "she", "show", "sing", "skill", "slave", "slow", "son", "star",
          "story", "subtract", "sudden", "suggest", "sun", "system"],
    "t": ["table", "talk", "temperature", "thin", "third", "though", "tail",
          "teeth", "thought", "tire", "told", "took", "track", "trip", "try",
          "thank", "teach", "there", "thousands", "time", "tool", "trade",
          "tree"],
    "u": ["under", "unit", "up", "usual"],
    "v": ["valley", "village", "value", "vowel", "view", "voice", "visit"],
    "w": ["want", "water", "week", "where", "what", "while", "window",
          "wire", "woman", "wonder", "write", "walk", "war", "wash", "wave",
          "wheel", "wish", "warm", "watch", "weather", "west", "wild", "word"],
    "y": ["yard", "yes", "young", "year", "yellow", "you", "yet"],
    "z": ["zebra"]
}

FILLERS = ["of", "to", "from", "was", "that", "which", "by", "about", "on"]
