#!/usr/bin/env python


import NumericalToolbox
import EncodingToolbox
import EncryptionToolbox
import argparse


def argument_handler():
    parser = argparse.ArgumentParser()
    parser.add_argument("-t", "--threshold", help="How many frequent letters?",
                        type=int, required=True)
    arg_group = parser.add_mutually_exclusive_group(required=True)
    arg_group.add_argument("-e", "--encrypt", help="Encrypt a text",
                           action='store_true')
    arg_group.add_argument("-d", "--decrypt", help="Decrypt a text",
                           action='store_true')
    args = parser.parse_args()
    return args.encrypt, args.decrypt, args.threshold


if __name__ == '__main__':
    encrypt, decrypt, threshold = argument_handler()
    if encrypt:
        raw_text = str(raw_input("What is your message? "))
        key = EncryptionToolbox.get_key()
        ciphertext = EncryptionToolbox.encrypt(raw_text, key)
        if threshold != 10:
            ciphertext = NumericalToolbox.change_base(ciphertext, 10, threshold)
        encoding = EncodingToolbox.encode(ciphertext, threshold)
    # elif decrypt:
    # decrypted_text = EncryptionToolbox.decrypt(ciphertext, key)
