#!/usr/bin/env python
"""
 Copyright 2016 Alireza Rafiei

 Licensed under the Apache License, Version 2.0 (the "License"); you may
 not use this file except in compliance with the License. You may obtain
 a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

import UIToolbox


if __name__ == '__main__':
    (should_encrypt, should_decrypt, plaintext, password, threshold, model_loc,
     textfile, is_interactive, silent) = UIToolbox.argument_handler()
    encrypt, decrypt, interactive, _ = UIToolbox.choice_handler()
    if is_interactive:
        interactive(model_loc, textfile, threshold, silent)
    else:
        if should_encrypt:
            encrypt(model_loc, textfile, plaintext=plaintext, password=password,
                    threshold=threshold, silent=silent)
        elif should_decrypt:
            decrypt(textfile, password=password, threshold=threshold,
                    silent=silent)
